### ISSUE TITLE
CITATION.cff file for citing repository

### ISSUE THREAD

**Issue by a-darcher** [Breakthrough/PySceneDetect#399]
**Use Case**

I use PySceneDetect as part of an on-going research project and want to cite it in a paper. I haven't found a preferred citation anywhere (hopefully have not missed something obvious). It might be useful to add a CITATION.cff file to the root directory to take advantage of the "Cite this repository" feature of GitHub repos (see [here](https://citation-file-format.github.io/)).

**Proposed Implementation:**

GitHub has a fill-in form/tool available [here.](https://citation-file-format.github.io/cff-initializer-javascript/#/)

**Examples:**

A possible example CITATION.cff file might be something like:
```
cff-version: 1.2.0
authors:
  - family-names: Castellano
    given-names: Brandon
title: "PySceneDetect"
version: 0.6.3
type: software
repository-code: 'https://github.com/Breakthrough/PySceneDetect/'
date-released: 2024-03-98
```
